@baseUrl = http://localhost:3000
@userId = 691af6ce679594af902955ed
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM2YjVhNjViYjMwZmE3NGRjNjRhYzkiLCJpYXQiOjE3NjY1NzE4OTEsImV4cCI6MTc2NjU5NzA5MX0.NO3qUJGZZkbkrIbWOAbGX1Rp02VoO1nYWShKcLEI3rQ


### Create a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe6@example.com",
  "password": "password"
}

### Get all users
GET {{baseUrl}}/users
Authorization: Bearer {{ token }}

### Get a user by id
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{ token }}

### Update a user by id
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe.updated@example.com",
  "password": "password2"
}

### Delete a user by id
DELETE {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{ token }}


### Register a new user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe7@example.com",
  "password": "password"
}

### Login a user
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "john.doe6@example.com",
  "password":"password"
}

### create a new trip
POST {{baseUrl}}/trip
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "title": "trip to the moon",
  "startDate": "2024-12-01",
  "endDate": "2024-12-10",
  "budget":{
    "total": 5000
  },
  "destination": ["Moon", "Mars", "Uranus"]
}

### Get all trips
GET {{baseUrl}}/trips
Authorization: Bearer {{token}}

### Get a trip by id
GET {{baseUrl}}/trips/6936b5a65bb30fa74dc64ac9
Authorization: Bearer {{token}}

### Invite collaborators to a trip
POST {{baseUrl}}/trips/693e9b8457a74bdcafa7d6cf/invite
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "collaboratorEmails": [
    "dbhattarai387@gmail.com",
    "pranish.dahal980@gmail.com"
    
  ]
}